// This file is auto-generated by @hey-api/openapi-ts

import { createClient, createConfig, type OptionsLegacyParser } from '@hey-api/client-axios';
import type { PostApiTemplateData, PostApiTemplateError, PostApiTemplateResponse, GetApiTemplateData, GetApiTemplateError, GetApiTemplateResponse, GetApiTemplateByIdData, GetApiTemplateByIdError, GetApiTemplateByIdResponse, PutApiTemplateByIdData, PutApiTemplateByIdError, PutApiTemplateByIdResponse, DeleteApiTemplateByIdData, DeleteApiTemplateByIdError, DeleteApiTemplateByIdResponse, PostApiTemplateByIdParametersData, PostApiTemplateByIdParametersError, PostApiTemplateByIdParametersResponse, GetApiTemplateByIdParametersData, GetApiTemplateByIdParametersError, GetApiTemplateByIdParametersResponse } from './types.gen';

export const client = createClient(createConfig());

export const postApiTemplate = <ThrowOnError extends boolean = false>(options?: OptionsLegacyParser<PostApiTemplateData, ThrowOnError>) => {
    return (options?.client ?? client).post<PostApiTemplateResponse, PostApiTemplateError, ThrowOnError>({
        ...options,
        url: '/api/Template'
    });
};

export const getApiTemplate = <ThrowOnError extends boolean = false>(options?: OptionsLegacyParser<GetApiTemplateData, ThrowOnError>) => {
    return (options?.client ?? client).get<GetApiTemplateResponse, GetApiTemplateError, ThrowOnError>({
        ...options,
        url: '/api/Template'
    });
};

export const getApiTemplateById = <ThrowOnError extends boolean = false>(options: OptionsLegacyParser<GetApiTemplateByIdData, ThrowOnError>) => {
    return (options?.client ?? client).get<GetApiTemplateByIdResponse, GetApiTemplateByIdError, ThrowOnError>({
        ...options,
        url: '/api/Template/{id}'
    });
};

export const putApiTemplateById = <ThrowOnError extends boolean = false>(options: OptionsLegacyParser<PutApiTemplateByIdData, ThrowOnError>) => {
    return (options?.client ?? client).put<PutApiTemplateByIdResponse, PutApiTemplateByIdError, ThrowOnError>({
        ...options,
        url: '/api/Template/{id}'
    });
};

export const deleteApiTemplateById = <ThrowOnError extends boolean = false>(options: OptionsLegacyParser<DeleteApiTemplateByIdData, ThrowOnError>) => {
    return (options?.client ?? client).delete<DeleteApiTemplateByIdResponse, DeleteApiTemplateByIdError, ThrowOnError>({
        ...options,
        url: '/api/Template/{id}'
    });
};

export const postApiTemplateByIdParameters = <ThrowOnError extends boolean = false>(options: OptionsLegacyParser<PostApiTemplateByIdParametersData, ThrowOnError>) => {
    return (options?.client ?? client).post<PostApiTemplateByIdParametersResponse, PostApiTemplateByIdParametersError, ThrowOnError>({
        ...options,
        url: '/api/Template/{id}/parameters'
    });
};

export const getApiTemplateByIdParameters = <ThrowOnError extends boolean = false>(options: OptionsLegacyParser<GetApiTemplateByIdParametersData, ThrowOnError>) => {
    return (options?.client ?? client).get<GetApiTemplateByIdParametersResponse, GetApiTemplateByIdParametersError, ThrowOnError>({
        ...options,
        url: '/api/Template/{id}/parameters'
    });
};