// This file is auto-generated by @hey-api/openapi-ts

export type Parameter = {
    key?: (string) | null;
    description?: (string) | null;
};

export type TemplateCreateDTO = {
    name?: (string) | null;
    content?: (string) | null;
    contentEn?: (string) | null;
    currentVersion?: (string) | null;
    author?: (string) | null;
    tags?: Array<(string)> | null;
};

export type TemplateUpdateDTO = {
    name?: (string) | null;
    content?: (string) | null;
    contentEn?: (string) | null;
    currentVersion?: (string) | null;
    author?: (string) | null;
    tags?: Array<(string)> | null;
};

export type PostApiTemplateData = {
    body?: TemplateCreateDTO;
};

export type PostApiTemplateResponse = (unknown);

export type PostApiTemplateError = unknown;

export type GetApiTemplateData = {
    query?: {
        Author?: string;
        CreatedAfter?: string;
        CreatedBefore?: string;
        CurrentVersion?: string;
        Name?: string;
        Tags?: Array<(string)>;
    };
};

export type GetApiTemplateResponse = (unknown);

export type GetApiTemplateError = unknown;

export type GetApiTemplateByIdData = {
    path: {
        id: string;
    };
};

export type GetApiTemplateByIdResponse = (unknown);

export type GetApiTemplateByIdError = unknown;

export type PutApiTemplateByIdData = {
    body?: TemplateUpdateDTO;
    path: {
        id: string;
    };
};

export type PutApiTemplateByIdResponse = (unknown);

export type PutApiTemplateByIdError = unknown;

export type DeleteApiTemplateByIdData = {
    path: {
        id: string;
    };
};

export type DeleteApiTemplateByIdResponse = (unknown);

export type DeleteApiTemplateByIdError = unknown;

export type PostApiTemplateByIdParametersData = {
    body?: Parameter;
    path: {
        id: string;
    };
};

export type PostApiTemplateByIdParametersResponse = (unknown);

export type PostApiTemplateByIdParametersError = unknown;

export type GetApiTemplateByIdParametersData = {
    path: {
        id: string;
    };
};

export type GetApiTemplateByIdParametersResponse = (unknown);

export type GetApiTemplateByIdParametersError = unknown;