// This file is auto-generated by @hey-api/openapi-ts

export const CategoryEnumSchema = {
  enum: [
    "customers",
    "suppliers",
    "chargeur",
    "receivers",
    "shippingLine",
    "shippingAgent",
  ],
  type: "string",
} as const;

export const OrderDtoSchema = {
  type: "object",
  properties: {
    orderId: {
      type: "integer",
      format: "int32",
    },
    customerId: {
      type: "integer",
      format: "int32",
    },
    sellerId: {
      type: "integer",
      format: "int32",
      nullable: true,
    },
    buyerId: {
      type: "integer",
      format: "int32",
      nullable: true,
    },
    refClient: {
      type: "string",
      nullable: true,
    },
    refSeller: {
      type: "string",
      nullable: true,
    },
    refBuyer: {
      type: "string",
      nullable: true,
    },
    incoTerm: {
      type: "string",
      nullable: true,
    },
    incotermDestination: {
      type: "string",
      nullable: true,
    },
    exportation: {
      type: "boolean",
      nullable: true,
    },
    city: {
      type: "integer",
      format: "int32",
      nullable: true,
    },
    cityIncotermTo: {
      type: "integer",
      format: "int32",
      nullable: true,
    },
    shipLineId: {
      type: "integer",
      format: "int32",
      nullable: true,
    },
    refShippingAgent: {
      type: "string",
      nullable: true,
    },
    shippingAgent: {
      type: "integer",
      format: "int32",
      nullable: true,
    },
    shipId: {
      type: "integer",
      format: "int32",
      nullable: true,
    },
    departurePortId: {
      type: "integer",
      format: "int32",
      nullable: true,
    },
    destinationPortId: {
      type: "integer",
      format: "int32",
      nullable: true,
    },
    estimatedDepartureDate: {
      type: "string",
      format: "date-time",
      nullable: true,
    },
    estimatedArrivalDate: {
      type: "string",
      format: "date-time",
      nullable: true,
    },
  },
  additionalProperties: false,
} as const;

export const OrderRoleEnumSchema = {
  enum: ["SAME_FOLDER", "INVOICE", "DOCUMENTATION", "OPERATIONS"],
  type: "string",
} as const;

export const OrderStatusEnumSchema = {
  enum: [
    "OPEN",
    "COMPLETED",
    "VALIDATED",
    "CLOSED",
    "CANCELLED",
    "DOCS_SENT",
    "PAID",
  ],
  type: "string",
} as const;

export const OrdersListDtoSchema = {
  type: "object",
  properties: {
    orderId: {
      type: "integer",
      format: "int32",
    },
    orderNumber: {
      type: "string",
      nullable: true,
    },
    orderDate: {
      type: "string",
      format: "date-time",
    },
    fiscalYear: {
      type: "integer",
      format: "int32",
    },
    customerName: {
      type: "string",
      nullable: true,
    },
    sellerName: {
      type: "string",
      nullable: true,
    },
    buyerName: {
      type: "string",
      nullable: true,
    },
    loadingPort: {
      type: "string",
      nullable: true,
    },
    dischargePort: {
      type: "string",
      nullable: true,
    },
    estimatedDepartureDate: {
      type: "string",
      format: "date-time",
      nullable: true,
    },
    estimatedArrivalDate: {
      type: "string",
      format: "date-time",
      nullable: true,
    },
    shipName: {
      type: "string",
      nullable: true,
    },
    shippingLine: {
      type: "string",
      nullable: true,
    },
    exportation: {
      type: "boolean",
      nullable: true,
    },
    orderStatus: {
      $ref: "#/components/schemas/OrderStatusEnum",
    },
    margin: {
      type: "number",
      format: "double",
      nullable: true,
    },
    ratio: {
      type: "number",
      format: "double",
      nullable: true,
    },
    incoming: {
      type: "number",
      format: "double",
      nullable: true,
    },
    outgoing: {
      type: "number",
      format: "double",
      nullable: true,
    },
  },
  additionalProperties: false,
} as const;

export const ResponseOrdersListDtoSchema = {
  type: "object",
  properties: {
    orders: {
      type: "array",
      items: {
        $ref: "#/components/schemas/OrdersListDto",
      },
      nullable: true,
    },
    margin: {
      type: "number",
      format: "double",
      nullable: true,
    },
    ratio: {
      type: "number",
      format: "double",
      nullable: true,
    },
    incoming: {
      type: "number",
      format: "double",
      nullable: true,
    },
    outgoing: {
      type: "number",
      format: "double",
      nullable: true,
    },
    averageMargin: {
      type: "number",
      format: "double",
      nullable: true,
    },
    displayBudgetDetails: {
      type: "boolean",
    },
  },
  additionalProperties: false,
} as const;
