// This file is auto-generated by @hey-api/openapi-ts

import { createClient, createConfig, type OptionsLegacyParser } from '@hey-api/client-axios';
import type { PostOrderData, PostOrderError, PostOrderResponse, GetOrdersData, GetOrdersError, GetOrdersResponse, GetOrderByIdData, GetOrderByIdError, GetOrderByIdResponse } from './types.gen';

export const client = createClient(createConfig());

/**
 * Create new order
 */
export const postOrder = <ThrowOnError extends boolean = false>(options?: OptionsLegacyParser<PostOrderData, ThrowOnError>) => {
    return (options?.client ?? client).post<PostOrderResponse, PostOrderError, ThrowOnError>({
        ...options,
        url: '/Order'
    });
};

/**
 * Get list orders in fonction parameters
 */
export const getOrders = <ThrowOnError extends boolean = false>(options?: OptionsLegacyParser<GetOrdersData, ThrowOnError>) => {
    return (options?.client ?? client).get<GetOrdersResponse, GetOrdersError, ThrowOnError>({
        ...options,
        url: '/Order/orders'
    });
};

/**
 * Get order by id
 */
export const getOrderById = <ThrowOnError extends boolean = false>(options: OptionsLegacyParser<GetOrderByIdData, ThrowOnError>) => {
    return (options?.client ?? client).get<GetOrderByIdResponse, GetOrderByIdError, ThrowOnError>({
        ...options,
        url: '/Order/{orderId}'
    });
};