// This file is auto-generated by @hey-api/openapi-ts

export enum CategoryEnum {
    CUSTOMERS = 'customers',
    SUPPLIERS = 'suppliers',
    CHARGEUR = 'chargeur',
    RECEIVERS = 'receivers',
    SHIPPING_LINE = 'shippingLine',
    SHIPPING_AGENT = 'shippingAgent'
}

export type OrderDto = {
    orderId?: number;
    customerId?: number;
    sellerId?: (number) | null;
    buyerId?: (number) | null;
    refClient?: (string) | null;
    refSeller?: (string) | null;
    refBuyer?: (string) | null;
    incoTerm?: (string) | null;
    incotermDestination?: (string) | null;
    exportation?: (boolean) | null;
    city?: (number) | null;
    cityIncotermTo?: (number) | null;
    shipLineId?: (number) | null;
    refShippingAgent?: (string) | null;
    shippingAgent?: (number) | null;
    shipId?: (number) | null;
    departurePortId?: (number) | null;
    destinationPortId?: (number) | null;
    estimatedDepartureDate?: (Date) | null;
    estimatedArrivalDate?: (Date) | null;
};

export enum OrderRoleEnum {
    SAME_FOLDER = 'SAME_FOLDER',
    INVOICE = 'INVOICE',
    DOCUMENTATION = 'DOCUMENTATION',
    OPERATIONS = 'OPERATIONS'
}

export type OrdersListDto = {
    orderId?: number;
    orderNumber?: (string) | null;
    orderDate?: Date;
    fiscalYear?: number;
    customerName?: (string) | null;
    sellerName?: (string) | null;
    buyerName?: (string) | null;
    loadingPort?: (string) | null;
    dischargePort?: (string) | null;
    estimatedDepartureDate?: (Date) | null;
    estimatedArrivalDate?: (Date) | null;
    shipName?: (string) | null;
    shippingLine?: (string) | null;
    exportation?: (boolean) | null;
    orderStatus?: OrderStatusEnum;
    margin?: (number) | null;
    ratio?: (number) | null;
    incoming?: (number) | null;
    outgoing?: (number) | null;
};

export enum OrderStatusEnum {
    OPEN = 'OPEN',
    COMPLETED = 'COMPLETED',
    VALIDATED = 'VALIDATED',
    CLOSED = 'CLOSED',
    CANCELLED = 'CANCELLED',
    DOCS_SENT = 'DOCS_SENT',
    PAID = 'PAID'
}

export type ResponseOrdersListDto = {
    orders?: Array<OrdersListDto> | null;
    margin?: (number) | null;
    ratio?: (number) | null;
    incoming?: (number) | null;
    outgoing?: (number) | null;
    averageMargin?: (number) | null;
    displayBudgetDetails?: boolean;
};

export type PostOrderData = {
    body?: OrderDto;
};

export type PostOrderResponse = (number);

export type PostOrderError = (unknown);

export type GetOrdersData = {
    query?: {
        AllFiles?: boolean;
        Contact?: number;
        ContactType?: CategoryEnum;
        ContainerNumber?: string;
        DischargePort?: number;
        Export?: boolean;
        Fiscal?: number;
        From?: Date;
        LoadingPort?: number;
        Month?: number;
        OrderRole?: OrderRoleEnum;
        Status?: OrderStatusEnum;
        To?: Date;
        UsersId?: Array<(number)>;
    };
};

export type GetOrdersResponse = (ResponseOrdersListDto);

export type GetOrdersError = (unknown);

export type GetOrderByIdData = {
    path: {
        /**
         * Identifiant
         */
        orderId: number;
    };
};

export type GetOrderByIdResponse = (OrderDto);

export type GetOrderByIdError = (unknown);

export type GetOrdersResponseTransformer = (data: any) => Promise<GetOrdersResponse>;

export type ResponseOrdersListDtoModelResponseTransformer = (data: any) => ResponseOrdersListDto;

export type OrdersListDtoModelResponseTransformer = (data: any) => OrdersListDto;

export const OrdersListDtoModelResponseTransformer: OrdersListDtoModelResponseTransformer = data => {
    if (data?.orderDate) {
        data.orderDate = new Date(data.orderDate);
    }
    if (data?.estimatedDepartureDate) {
        data.estimatedDepartureDate = new Date(data.estimatedDepartureDate);
    }
    if (data?.estimatedArrivalDate) {
        data.estimatedArrivalDate = new Date(data.estimatedArrivalDate);
    }
    return data;
};

export const ResponseOrdersListDtoModelResponseTransformer: ResponseOrdersListDtoModelResponseTransformer = data => {
    if (Array.isArray(data?.orders)) {
        data.orders.forEach(OrdersListDtoModelResponseTransformer);
    }
    return data;
};

export const GetOrdersResponseTransformer: GetOrdersResponseTransformer = async (data) => {
    ResponseOrdersListDtoModelResponseTransformer(data);
    return data;
};

export type GetOrderByIdResponseTransformer = (data: any) => Promise<GetOrderByIdResponse>;

export type OrderDtoModelResponseTransformer = (data: any) => OrderDto;

export const OrderDtoModelResponseTransformer: OrderDtoModelResponseTransformer = data => {
    if (data?.estimatedDepartureDate) {
        data.estimatedDepartureDate = new Date(data.estimatedDepartureDate);
    }
    if (data?.estimatedArrivalDate) {
        data.estimatedArrivalDate = new Date(data.estimatedArrivalDate);
    }
    return data;
};

export const GetOrderByIdResponseTransformer: GetOrderByIdResponseTransformer = async (data) => {
    OrderDtoModelResponseTransformer(data);
    return data;
};