// This file is auto-generated by @hey-api/openapi-ts

import type { OptionsLegacyParser } from '@hey-api/client-axios';
import { queryOptions, type UseMutationOptions } from '@tanstack/react-query';
import type { PostOrderData, PostOrderError, PostOrderResponse, GetOrdersData, GetOrderByIdData } from '../types.gen';
import type { AxiosError } from 'axios';
import { client, postOrder, getOrders, getOrderById } from '../sdk.gen';

type QueryKey<TOptions extends OptionsLegacyParser> = [
    Pick<TOptions, 'baseURL' | 'body' | 'headers' | 'path' | 'query'> & {
        _id: string;
        _infinite?: boolean;
    }
];

const createQueryKey = <TOptions extends OptionsLegacyParser>(id: string, options?: TOptions, infinite?: boolean): QueryKey<TOptions>[0] => {
    const params: QueryKey<TOptions>[0] = { _id: id, baseURL: (options?.client ?? client).getConfig().baseURL } as QueryKey<TOptions>[0];
    if (infinite) {
        params._infinite = infinite;
    }
    if (options?.body) {
        params.body = options.body;
    }
    if (options?.headers) {
        params.headers = options.headers;
    }
    if (options?.path) {
        params.path = options.path;
    }
    if (options?.query) {
        params.query = options.query;
    }
    return params;
};

export const postOrderQueryKey = (options?: OptionsLegacyParser<PostOrderData>) => [
    createQueryKey('postOrder', options)
];

export const postOrderOptions = (options?: OptionsLegacyParser<PostOrderData>) => {
    return queryOptions({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await postOrder({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: postOrderQueryKey(options)
    });
};

export const postOrderMutation = (options?: Partial<OptionsLegacyParser<PostOrderData>>) => {
    const mutationOptions: UseMutationOptions<PostOrderResponse, AxiosError<PostOrderError>, OptionsLegacyParser<PostOrderData>> = {
        mutationFn: async (localOptions) => {
            const { data } = await postOrder({
                ...options,
                ...localOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const getOrdersQueryKey = (options?: OptionsLegacyParser<GetOrdersData>) => [
    createQueryKey('getOrders', options)
];

export const getOrdersOptions = (options?: OptionsLegacyParser<GetOrdersData>) => {
    return queryOptions({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await getOrders({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: getOrdersQueryKey(options)
    });
};

export const getOrderByIdQueryKey = (options: OptionsLegacyParser<GetOrderByIdData>) => [
    createQueryKey('getOrderById', options)
];

export const getOrderByIdOptions = (options: OptionsLegacyParser<GetOrderByIdData>) => {
    return queryOptions({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await getOrderById({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: getOrderByIdQueryKey(options)
    });
};