// This file is auto-generated by @hey-api/openapi-ts

export type BooleanApiResponse = {
    code?: (string) | null;
    message?: (string) | null;
    data?: boolean;
    error?: (string) | null;
};

export type ContactViewModel = {
    contactId?: number;
    contactNumber?: (string) | null;
    contactName?: (string) | null;
    email?: (string) | null;
    phone?: (string) | null;
    celPhone?: (string) | null;
    categories?: Array<('CUSTOMERS' | 'SUPPLIERS' | 'CHARGEUR' | 'RECEIVER' | 'SHIPPING_LINES' | 'BANK' | 'SHIPPING_AGENCY11')> | null;
};

export type ContactViewModelApiResponse = {
    code?: (string) | null;
    message?: (string) | null;
    data?: ContactViewModel;
    error?: (string) | null;
};

export type ContactViewModelListApiResponse = {
    code?: (string) | null;
    message?: (string) | null;
    data?: Array<ContactViewModel> | null;
    error?: (string) | null;
};

export type CreateContactViewModel = {
    contactName?: (string) | null;
    addressCountry?: (string) | null;
    createdBy?: (number) | null;
    countryCode?: (string) | null;
    phone?: (string) | null;
    email?: (string) | null;
    categories?: Array<(string)> | null;
};

export type Int32ApiResponse = {
    code?: (string) | null;
    message?: (string) | null;
    data?: number;
    error?: (string) | null;
};

export type UpdateContactViewModel = {
    contactName?: (string) | null;
    addressCountry?: (string) | null;
    createdBy?: (number) | null;
    countryCode?: (string) | null;
    phone?: (string) | null;
    email?: (string) | null;
    categories?: Array<(string)> | null;
};

export type GetContactGetContactsData = {
    query?: {
        category?: 'CUSTOMERS' | 'SUPPLIERS' | 'CHARGEUR' | 'RECEIVER' | 'SHIPPING_LINES' | 'BANK' | 'SHIPPING_AGENCY11';
        contactName?: string;
        contactNumber?: string;
    };
};

export type GetContactGetContactsResponse = (ContactViewModelListApiResponse);

export type GetContactGetContactsError = unknown;

export type PostContactCreateContactData = {
    body?: CreateContactViewModel;
};

export type PostContactCreateContactResponse = (Int32ApiResponse);

export type PostContactCreateContactError = (unknown);

export type GetContactGetContactByIdByIdData = {
    path: {
        id: number;
    };
};

export type GetContactGetContactByIdByIdResponse = (ContactViewModelApiResponse);

export type GetContactGetContactByIdByIdError = (unknown);

export type PutContactUpdateContactByIdData = {
    body?: UpdateContactViewModel;
    path: {
        id: number;
    };
};

export type PutContactUpdateContactByIdResponse = (BooleanApiResponse);

export type PutContactUpdateContactByIdError = (unknown);

export type DeleteContactDeleteContactByIdData = {
    path: {
        id: number;
    };
};

export type DeleteContactDeleteContactByIdResponse = (BooleanApiResponse);

export type DeleteContactDeleteContactByIdError = (unknown);