// This file is auto-generated by @hey-api/openapi-ts

export type CityViewModel = {
    id?: number;
    name?: (string) | null;
    country?: (string) | null;
};

export type ContainerViewModel = {
    packageId?: number;
    packageName?: (string) | null;
};

export type CreatedServiceViewModel = {
    serviceName?: (string) | null;
    serviceDescription?: (string) | null;
    servicesTypeId?: Array<(number)> | null;
};

export type PortViewModel = {
    portId?: number;
    portName?: (string) | null;
    country?: (string) | null;
};

export type ProductViewModel = {
    productId?: number;
    productName?: (string) | null;
};

export type ServiceViewModel = {
    serviceId?: number;
    serviceName?: (string) | null;
    servicesTypeId?: Array<(number)> | null;
};

export type GetCityCitiesResponse = (Array<CityViewModel>);

export type GetCityCitiesError = unknown;

export type GetPackageContainersData = {
    query?: {
        containerOnlyUsed?: boolean;
    };
};

export type GetPackageContainersResponse = (Array<ContainerViewModel>);

export type GetPackageContainersError = unknown;

export type GetPortsData = {
    query?: {
        country?: string;
        page?: number;
        pageSize?: number;
        portName?: string;
    };
};

export type GetPortsResponse = (Array<PortViewModel>);

export type GetPortsError = unknown;

export type GetPortData = {
    path: {
        id: number;
    };
};

export type GetPortResponse = (PortViewModel);

export type GetPortError = unknown;

export type CreatePortData = {
    body?: PortViewModel;
};

export type CreatePortResponse = (PortViewModel);

export type CreatePortError = unknown;

export type UpdatePortData = {
    body?: PortViewModel;
    path: {
        id: number;
    };
};

export type UpdatePortResponse = (unknown);

export type UpdatePortError = unknown;

export type DeletePortData = {
    path: {
        id: number;
    };
};

export type DeletePortResponse = (unknown);

export type DeletePortError = unknown;

export type GetProductData = {
    query?: {
        page?: number;
        pageSize?: number;
        productName?: string;
    };
};

export type GetProductResponse = (Array<ProductViewModel>);

export type GetProductError = unknown;

export type PostProductData = {
    body?: ProductViewModel;
};

export type PostProductResponse = (ProductViewModel);

export type PostProductError = unknown;

export type GetProductByIdData = {
    path: {
        id: number;
    };
};

export type GetProductByIdResponse = (ProductViewModel);

export type GetProductByIdError = unknown;

export type PutProductByIdData = {
    body?: ProductViewModel;
    path: {
        id: number;
    };
};

export type PutProductByIdResponse = (unknown);

export type PutProductByIdError = unknown;

export type DeleteProductByIdData = {
    path: {
        id: number;
    };
};

export type DeleteProductByIdResponse = (unknown);

export type DeleteProductByIdError = unknown;

export type PostServiceData = {
    body?: CreatedServiceViewModel;
};

export type PostServiceResponse = (number);

export type PostServiceError = unknown;

export type GetServiceData = {
    query?: {
        pageNumber?: number;
        pageSize?: number;
        serviceName?: string;
        servicesTypeId?: Array<(number)>;
    };
};

export type GetServiceResponse = (Array<ServiceViewModel>);

export type GetServiceError = unknown;

export type GetServiceByServiceIdData = {
    path: {
        serviceId: number;
    };
};

export type GetServiceByServiceIdResponse = (ServiceViewModel);

export type GetServiceByServiceIdError = unknown;

export type PutServiceByServiceIdData = {
    body?: ServiceViewModel;
    path: {
        serviceId: number;
    };
};

export type PutServiceByServiceIdResponse = (unknown);

export type PutServiceByServiceIdError = unknown;

export type DeleteServiceByServiceIdData = {
    path: {
        serviceId: number;
    };
};

export type DeleteServiceByServiceIdResponse = (unknown);

export type DeleteServiceByServiceIdError = unknown;