// This file is auto-generated by @hey-api/openapi-ts

import { createClient, createConfig, type OptionsLegacyParser } from '@hey-api/client-axios';
import type { GetApiProcessStateByUserIdByProcessNameData, GetApiProcessStateByUserIdByProcessNameError, GetApiProcessStateByUserIdByProcessNameResponse, PostApiProcessStateData, PostApiProcessStateError, PostApiProcessStateResponse, DeleteApiProcessStateByStateIdData, DeleteApiProcessStateByStateIdError, DeleteApiProcessStateByStateIdResponse } from './types.gen';

export const client = createClient(createConfig());

export const getApiProcessStateByUserIdByProcessName = <ThrowOnError extends boolean = false>(options: OptionsLegacyParser<GetApiProcessStateByUserIdByProcessNameData, ThrowOnError>) => {
    return (options?.client ?? client).get<GetApiProcessStateByUserIdByProcessNameResponse, GetApiProcessStateByUserIdByProcessNameError, ThrowOnError>({
        ...options,
        url: '/api/ProcessState/{userId}/{processName}'
    });
};

export const postApiProcessState = <ThrowOnError extends boolean = false>(options?: OptionsLegacyParser<PostApiProcessStateData, ThrowOnError>) => {
    return (options?.client ?? client).post<PostApiProcessStateResponse, PostApiProcessStateError, ThrowOnError>({
        ...options,
        url: '/api/ProcessState'
    });
};

export const deleteApiProcessStateByStateId = <ThrowOnError extends boolean = false>(options: OptionsLegacyParser<DeleteApiProcessStateByStateIdData, ThrowOnError>) => {
    return (options?.client ?? client).delete<DeleteApiProcessStateByStateIdResponse, DeleteApiProcessStateByStateIdError, ThrowOnError>({
        ...options,
        url: '/api/ProcessState/{stateId}'
    });
};