// This file is auto-generated by @hey-api/openapi-ts

export type ProcessState = {
    id?: (string) | null;
    userId?: (string) | null;
    processName?: (string) | null;
    stateData?: (string) | null;
    createdAt?: Date;
    expiresAt?: (Date) | null;
};

export type SaveProcessStateRequest = {
    userId?: (string) | null;
    processName?: (string) | null;
    stateData?: (string) | null;
    isShared?: boolean;
    expiresIn?: (string) | null;
};

export type GetApiProcessStateByUserIdByProcessNameData = {
    path: {
        processName: string;
        userId: string;
    };
};

export type GetApiProcessStateByUserIdByProcessNameResponse = (ProcessState);

export type GetApiProcessStateByUserIdByProcessNameError = unknown;

export type PostApiProcessStateData = {
    body?: SaveProcessStateRequest;
};

export type PostApiProcessStateResponse = (unknown);

export type PostApiProcessStateError = unknown;

export type DeleteApiProcessStateByStateIdData = {
    path: {
        stateId: string;
    };
};

export type DeleteApiProcessStateByStateIdResponse = (unknown);

export type DeleteApiProcessStateByStateIdError = unknown;

export type GetApiProcessStateByUserIdByProcessNameResponseTransformer = (data: any) => Promise<GetApiProcessStateByUserIdByProcessNameResponse>;

export type ProcessStateModelResponseTransformer = (data: any) => ProcessState;

export const ProcessStateModelResponseTransformer: ProcessStateModelResponseTransformer = data => {
    if (data?.createdAt) {
        data.createdAt = new Date(data.createdAt);
    }
    if (data?.expiresAt) {
        data.expiresAt = new Date(data.expiresAt);
    }
    return data;
};

export const GetApiProcessStateByUserIdByProcessNameResponseTransformer: GetApiProcessStateByUserIdByProcessNameResponseTransformer = async (data) => {
    ProcessStateModelResponseTransformer(data);
    return data;
};