// This file is auto-generated by @hey-api/openapi-ts

export type Assignee = {
    id?: number;
    name: string;
    email: string;
    idUser?: (string) | null;
};

export type ChangeStatusRequest = {
    newStatus?: StatusRequest;
    customMessage?: (string) | null;
};

export type Container = {
    id?: number;
    containers?: (string) | null;
    quantity?: number;
};

export type EmailConfig = {
    id?: number;
    adminEmail: string;
    fromEmail: string;
};

export type GraphApiUser = {
    id?: (string) | null;
};

export type HSCodeLIS = {
    hS_Code?: number;
    _4_digit_categories?: (string) | null;
    product_description_En?: (string) | null;
    product_description_Fr?: (string) | null;
    product_description_NL?: (string) | null;
};

export type NoteType = 'Automatic' | 'General' | 'CustomStatusChange' | 'InformationRequest';

export type RequestQuote = {
    id?: number;
    whatsapp: string;
    email: string;
    departure: string;
    arrival: string;
    status?: StatusRequest;
    cargoType: TypeOfCargo;
    quantity: number;
    detail?: (string) | null;
    createdAt?: (string) | null;
    updatedAt?: (string) | null;
    tags?: (string) | null;
    trackingNumber?: (string) | null;
    creator?: (string) | null;
    assigneeId?: (number) | null;
    assignee?: Assignee;
    notes?: Array<RequestQuoteNote> | null;
    packingType?: (string) | null;
    clientNumber?: (string) | null;
    containersJson?: (string) | null;
    unitsJson?: (string) | null;
    containers?: Array<Container> | null;
    units?: Array<Unit> | null;
};

export type RequestQuoteHistory = {
    id?: number;
    requestQuoteId: number;
    assigneeId?: (number) | null;
    assignee?: Assignee;
    assignedAt?: string;
    unassignedAt?: (string) | null;
};

export type RequestQuoteNote = {
    id?: number;
    content?: (string) | null;
    createdAt?: string;
    requestQuoteId?: number;
    isInternal?: boolean;
    noteType?: NoteType;
    subject?: (string) | null;
    email?: (string) | null;
    idUser?: (string) | null;
};

export type StatusRequest = 'New' | 'EnAttente' | 'Valider' | 'Rejeter' | 'EnCoursDeTraitement' | 'EnTransit' | 'EnDouane' | 'LivraisonEnCours' | 'Livre' | 'Annule' | 'Retour' | 'Problème' | 'EnAttenteDeFacturation';

export type TypeOfCargo = 'Container' | 'Conventional' | 'RollOnRollOff';

export type Unit = {
    id?: number;
    name?: (string) | null;
    weight?: number;
    dimension?: (string) | null;
    quantity?: number;
};

export type GetApiAssigneeData = {
    query?: {
        nameFilter?: string;
        userIdFilter?: string;
    };
};

export type GetApiAssigneeResponse = (Array<Assignee>);

export type GetApiAssigneeError = unknown;

export type PostApiAssigneeData = {
    body?: Assignee;
};

export type PostApiAssigneeResponse = (Assignee);

export type PostApiAssigneeError = unknown;

export type GetApiAssigneeByIdData = {
    path: {
        id: number;
    };
};

export type GetApiAssigneeByIdResponse = (Assignee);

export type GetApiAssigneeByIdError = unknown;

export type PutApiAssigneeByIdData = {
    body?: Assignee;
    path: {
        id: number;
    };
};

export type PutApiAssigneeByIdResponse = (unknown);

export type PutApiAssigneeByIdError = unknown;

export type DeleteApiAssigneeByIdData = {
    path: {
        id: number;
    };
};

export type DeleteApiAssigneeByIdResponse = (unknown);

export type DeleteApiAssigneeByIdError = unknown;

export type PutApiAssigneeByRequestQuoteIdByAssigneeIdData = {
    path: {
        assigneeId: number;
        requestQuoteId: number;
    };
};

export type PutApiAssigneeByRequestQuoteIdByAssigneeIdResponse = (unknown);

export type PutApiAssigneeByRequestQuoteIdByAssigneeIdError = unknown;

export type PutApiAssigneeUnassignByRequestQuoteIdData = {
    path: {
        requestQuoteId: number;
    };
};

export type PutApiAssigneeUnassignByRequestQuoteIdResponse = (unknown);

export type PutApiAssigneeUnassignByRequestQuoteIdError = unknown;

export type PostApiEmailData = {
    body?: {
        From?: string;
        To?: string;
        Subject?: string;
        HtmlContent?: string;
        Attachments?: Array<((Blob | File))>;
    };
};

export type PostApiEmailResponse = (unknown);

export type PostApiEmailError = unknown;

export type GetEmailConfigResponse = (unknown);

export type GetEmailConfigError = unknown;

export type PutEmailConfigData = {
    body?: EmailConfig;
};

export type PutEmailConfigResponse = (unknown);

export type PutEmailConfigError = unknown;

export type PostEmailConfigData = {
    body?: EmailConfig;
};

export type PostEmailConfigResponse = (unknown);

export type PostEmailConfigError = unknown;

export type PostApiFileUploadData = {
    body?: {
        file?: (Blob | File);
    };
};

export type PostApiFileUploadResponse = (unknown);

export type PostApiFileUploadError = unknown;

export type GetApiFileByBlobNameData = {
    path: {
        blobName: string;
    };
};

export type GetApiFileByBlobNameResponse = (unknown);

export type GetApiFileByBlobNameError = unknown;

export type DeleteApiFileByBlobNameData = {
    path: {
        blobName: string;
    };
};

export type DeleteApiFileByBlobNameResponse = (unknown);

export type DeleteApiFileByBlobNameError = unknown;

export type GetApiFileUriByBlobNameData = {
    path: {
        blobName: string;
    };
};

export type GetApiFileUriByBlobNameResponse = (unknown);

export type GetApiFileUriByBlobNameError = unknown;

export type GetApiHsCodeLisResponse = (Array<HSCodeLIS>);

export type GetApiHsCodeLisError = unknown;

export type PostApiHsCodeLisData = {
    body?: HSCodeLIS;
};

export type PostApiHsCodeLisResponse = (HSCodeLIS);

export type PostApiHsCodeLisError = unknown;

export type GetApiHsCodeLisByIdData = {
    path: {
        id: number;
    };
};

export type GetApiHsCodeLisByIdResponse = (HSCodeLIS);

export type GetApiHsCodeLisByIdError = unknown;

export type PutApiHsCodeLisByIdData = {
    body?: HSCodeLIS;
    path: {
        id: number;
    };
};

export type PutApiHsCodeLisByIdResponse = (unknown);

export type PutApiHsCodeLisByIdError = unknown;

export type DeleteApiHsCodeLisByIdData = {
    path: {
        id: number;
    };
};

export type DeleteApiHsCodeLisByIdResponse = (unknown);

export type DeleteApiHsCodeLisByIdError = unknown;

export type GetApiRequestData = {
    query?: {
        Arrival?: string;
        AssigneeId?: number;
        CargoType?: string;
        ClientNumber?: string;
        CreatedAtEnd?: string;
        CreatedAtStart?: string;
        Creator?: string;
        Departure?: string;
        PackingType?: string;
        Search?: string;
        Status?: string;
        Tags?: string;
        UpdatedAtEnd?: string;
        UpdatedAtStart?: string;
    };
};

export type GetApiRequestResponse = (unknown);

export type GetApiRequestError = unknown;

export type PostApiRequestData = {
    body: RequestQuote;
};

export type PostApiRequestResponse = (unknown);

export type PostApiRequestError = unknown;

export type GetApiRequestByIdData = {
    path: {
        id: number;
    };
};

export type GetApiRequestByIdResponse = (unknown);

export type GetApiRequestByIdError = unknown;

export type PutApiRequestByIdData = {
    body?: RequestQuote;
    path: {
        id: number;
    };
};

export type PutApiRequestByIdResponse = (unknown);

export type PutApiRequestByIdError = unknown;

export type DeleteApiRequestByIdData = {
    path: {
        id: number;
    };
};

export type DeleteApiRequestByIdResponse = (unknown);

export type DeleteApiRequestByIdError = unknown;

export type PutApiRequestByIdChangeStatusData = {
    body?: ChangeStatusRequest;
    path: {
        id: number;
    };
};

export type PutApiRequestByIdChangeStatusResponse = (unknown);

export type PutApiRequestByIdChangeStatusError = unknown;

export type GetApiRequestQuoteHistoryData = {
    query?: {
        assigneeId?: number;
        endDate?: string;
        requestQuoteId?: number;
        startDate?: string;
    };
};

export type GetApiRequestQuoteHistoryResponse = (unknown);

export type GetApiRequestQuoteHistoryError = unknown;

export type PostApiRequestQuoteHistoryData = {
    body?: RequestQuoteHistory;
};

export type PostApiRequestQuoteHistoryResponse = (unknown);

export type PostApiRequestQuoteHistoryError = unknown;

export type GetApiRequestQuoteHistoryByIdData = {
    path: {
        id: number;
    };
};

export type GetApiRequestQuoteHistoryByIdResponse = (unknown);

export type GetApiRequestQuoteHistoryByIdError = unknown;

export type PutApiRequestQuoteHistoryByIdData = {
    body?: RequestQuoteHistory;
    path: {
        id: number;
    };
};

export type PutApiRequestQuoteHistoryByIdResponse = (unknown);

export type PutApiRequestQuoteHistoryByIdError = unknown;

export type DeleteApiRequestQuoteHistoryByIdData = {
    path: {
        id: number;
    };
};

export type DeleteApiRequestQuoteHistoryByIdResponse = (unknown);

export type DeleteApiRequestQuoteHistoryByIdError = unknown;

export type GetApiRequestQuoteNotesData = {
    query?: {
        createdAtFrom?: string;
        createdAtTo?: string;
        isInternal?: boolean;
        noteType?: NoteType;
        requestQuoteId?: number;
        userIdFilter?: string;
    };
};

export type GetApiRequestQuoteNotesResponse = (unknown);

export type GetApiRequestQuoteNotesError = unknown;

export type PostApiRequestQuoteNotesData = {
    body?: RequestQuoteNote;
};

export type PostApiRequestQuoteNotesResponse = (unknown);

export type PostApiRequestQuoteNotesError = unknown;

export type GetApiRequestQuoteNotesByIdData = {
    path: {
        id: number;
    };
};

export type GetApiRequestQuoteNotesByIdResponse = (unknown);

export type GetApiRequestQuoteNotesByIdError = unknown;

export type PutApiRequestQuoteNotesByIdData = {
    body?: RequestQuoteNote;
    path: {
        id: number;
    };
};

export type PutApiRequestQuoteNotesByIdResponse = (unknown);

export type PutApiRequestQuoteNotesByIdError = unknown;

export type DeleteApiRequestQuoteNotesByIdData = {
    path: {
        id: number;
    };
};

export type DeleteApiRequestQuoteNotesByIdResponse = (unknown);

export type DeleteApiRequestQuoteNotesByIdError = unknown;

export type PostApiSmsSendData = {
    query?: {
        fromPhoneNumber?: string;
        messageText?: string;
        toPhoneNumber?: string;
    };
};

export type PostApiSmsSendResponse = (unknown);

export type PostApiSmsSendError = unknown;

export type GetApiTrackingByTrackingNumberData = {
    path: {
        trackingNumber: string;
    };
};

export type GetApiTrackingByTrackingNumberResponse = (unknown);

export type GetApiTrackingByTrackingNumberError = unknown;

export type PostUserGroupUsersByUserIdData = {
    path: {
        userId: string;
    };
};

export type PostUserGroupUsersByUserIdResponse = (unknown);

export type PostUserGroupUsersByUserIdError = unknown;

export type DeleteUserGroupUsersByUserIdData = {
    path: {
        userId: string;
    };
};

export type DeleteUserGroupUsersByUserIdResponse = (unknown);

export type DeleteUserGroupUsersByUserIdError = unknown;

export type GetUserGroupUsersResponse = (Array<GraphApiUser>);

export type GetUserGroupUsersError = unknown;

export type PostWhatsAppSendmessageData = {
    query?: {
        fromWhatsAppNumber?: string;
        messageText?: string;
        toPhoneNumber?: string;
    };
};

export type PostWhatsAppSendmessageResponse = (unknown);

export type PostWhatsAppSendmessageError = unknown;