// This file is auto-generated by @hey-api/openapi-ts

export const FileDtoSchema = {
  type: "object",
  properties: {
    fileBase64: {
      type: "string",
      nullable: true,
    },
    blobName: {
      type: "string",
      nullable: true,
    },
    contentType: {
      type: "string",
      nullable: true,
    },
  },
  additionalProperties: false,
} as const;
