// This file is auto-generated by @hey-api/openapi-ts

export type FileDto = {
  fileBase64?: string | null;
  blobName?: string | null;
  contentType?: string | null;
};

export type PostApiFileUploadData = {
  body?: {
    file?: Blob | File;
  };
  query?: {
    folder?: string;
  };
};

export type PostApiFileUploadResponse = unknown;

export type PostApiFileUploadError = unknown;

export type GetApiFileByFolderByFileNameData = {
  path: {
    fileName: string;
    folder: string;
  };
};

export type GetApiFileByFolderByFileNameResponse = FileDto;

export type GetApiFileByFolderByFileNameError = unknown;

export type DeleteApiFileByFolderByFileNameData = {
  path: {
    fileName: string;
    folder: string;
  };
};

export type DeleteApiFileByFolderByFileNameResponse = unknown;

export type DeleteApiFileByFolderByFileNameError = unknown;

export type GetApiFileByFolderData = {
  path: {
    folder: string;
  };
};

export type GetApiFileByFolderResponse = Array<FileDto>;

export type GetApiFileByFolderError = unknown;
