// This file is auto-generated by @hey-api/openapi-ts

export type ClientApprovalStatus = 'Pending' | 'Accepted' | 'Rejected' | 'NoResponse';

export type Container = {
    readonly id?: (string) | null;
    containerId?: number;
    quantity?: number;
};

export type ContainerService = {
    container?: Container;
    services?: Array<Service> | null;
};

export type CreateQuoteOfferViewModel = {
    requestQuoteId?: number;
    comment?: (string) | null;
    quoteOfferNumber?: (number) | null;
    emailUser?: (string) | null;
    options?: Array<Option> | null;
    files?: Array<File> | null;
    selectedOption?: number;
    clientNumber?: (string) | null;
};

export type File = {
    readonly id?: (string) | null;
    fileName?: (string) | null;
    contentType?: (string) | null;
    size?: number;
    uploadedAt?: string;
    url?: (string) | null;
};

export type Haulage = {
    readonly id?: (string) | null;
    haulierId?: number;
    haulierName?: (string) | null;
    validUntil?: string;
    loadingPortId?: number;
    loadingPort?: (string) | null;
    currency?: (string) | null;
    loadingCityName?: (string) | null;
    freeTime?: number;
    multiStop?: number;
    overtimeTariff?: number;
    unitTariff?: number;
    containerNames?: Array<(string)> | null;
    comment?: (string) | null;
    updated?: string;
    created?: string;
};

export type Miscellaneous = {
    miscellaneousId?: (string) | null;
    supplierName?: (string) | null;
    currency?: (string) | null;
    total20Dry?: number;
    total40Dry?: number;
    total20Hcrf?: number;
    total40Hc?: number;
    total20Rf?: number;
    total20?: number;
    total40?: number;
    services?: Array<Miscellaneous_Service> | null;
    validUntil?: string;
    created?: string;
    updated?: (string) | null;
    containers?: Array<MiscellaneousContainer> | null;
    textServices?: (string) | null;
    costTotal?: number;
    defaultContainer?: (string) | null;
};

export type Miscellaneous_Service = {
    serviceId?: number;
    serviceName?: (string) | null;
    price?: number;
    containers?: Array<MiscellaneousContainer> | null;
};

export type MiscellaneousContainer = {
    packageId?: number;
    packageName?: (string) | null;
};

export type Option = {
    selectedHaulage?: Haulage;
    selectedSeafreight?: SeaFreight;
    myMiscs?: Array<Miscellaneous> | null;
    portDeparture?: Port;
    portDestination?: Port;
    selectedSeafreights?: Array<SeaFreight> | null;
};

export type Package = {
    id?: (string) | null;
    packageName?: (string) | null;
};

export type Port = {
    readonly id?: (string) | null;
    portId?: number;
    portName?: (string) | null;
    country?: (string) | null;
    name?: (string) | null;
    coordinates?: Array<(number)> | null;
};

export type QuoteOfferStatus = 'Pending' | 'Accepted' | 'Rejected' | 'NoResponse' | 'Exhale';

export type QuoteOfferUpdateModel = {
    requestQuoteId?: number;
    comment?: (string) | null;
    quoteOfferNumber?: (number) | null;
    emailUser?: (string) | null;
    options?: Array<Option> | null;
    files?: Array<File> | null;
    selectedOption?: number;
    clientNumber?: (string) | null;
};

export type SeaFreight = {
    readonly id?: (string) | null;
    seaFreightId?: (string) | null;
    departurePortName?: (string) | null;
    destinationPortName?: (string) | null;
    validUntil?: string;
    carrierName?: (string) | null;
    carrierAgentName?: (string) | null;
    price20Dry?: number;
    price20Rf?: number;
    price40Dry?: number;
    price40Hc?: number;
    price40Hcrf?: number;
    transitTime?: number;
    frequency?: number;
    currency?: (string) | null;
    comment?: (string) | null;
    lastUpdated?: string;
    created?: string;
    containers?: Array<ContainerService> | null;
    defaultContainer?: (string) | null;
};

export type Service = {
    readonly id?: (string) | null;
    serviceName?: (string) | null;
    price?: number;
};

export type GetApiPackageData = {
    query?: {
        PackageName?: string;
    };
};

export type GetApiPackageResponse = (unknown);

export type GetApiPackageError = unknown;

export type PostApiPackageData = {
    body?: Package;
};

export type PostApiPackageResponse = (unknown);

export type PostApiPackageError = unknown;

export type GetPackageData = {
    path: {
        id: string;
    };
};

export type GetPackageResponse = (unknown);

export type GetPackageError = unknown;

export type PutApiPackageByIdData = {
    body?: Package;
    path: {
        id: string;
    };
};

export type PutApiPackageByIdResponse = (unknown);

export type PutApiPackageByIdError = unknown;

export type DeleteApiPackageByIdData = {
    path: {
        id: string;
    };
};

export type DeleteApiPackageByIdResponse = (unknown);

export type DeleteApiPackageByIdError = unknown;

export type GetApiQuoteOfferData = {
    query?: {
        ClientApproval?: ClientApprovalStatus;
        clientNumber?: string;
        Created?: string;
        CreatedBy?: string;
        EmailUser?: string;
        ExpirationDate?: string;
        HaulageId?: string;
        MiscellaneousIds?: Array<(string)>;
        QuoteOfferNumber?: number;
        RequestQuoteId?: number;
        SeaFreightId?: string;
        Status?: QuoteOfferStatus;
    };
};

export type GetApiQuoteOfferResponse = (unknown);

export type GetApiQuoteOfferError = unknown;

export type PostApiQuoteOfferData = {
    body?: CreateQuoteOfferViewModel;
};

export type PostApiQuoteOfferResponse = (unknown);

export type PostApiQuoteOfferError = unknown;

export type GetQuoteOfferData = {
    path: {
        id: string;
    };
};

export type GetQuoteOfferResponse = (unknown);

export type GetQuoteOfferError = unknown;

export type PutApiQuoteOfferByIdData = {
    body?: QuoteOfferUpdateModel;
    path: {
        id: string;
    };
};

export type PutApiQuoteOfferByIdResponse = (unknown);

export type PutApiQuoteOfferByIdError = unknown;

export type DeleteApiQuoteOfferByIdData = {
    path: {
        id: string;
    };
};

export type DeleteApiQuoteOfferByIdResponse = (unknown);

export type DeleteApiQuoteOfferByIdError = unknown;

export type PutApiQuoteOfferByIdStatusData = {
    path: {
        id: string;
    };
    query?: {
        newStatus?: QuoteOfferStatus;
    };
};

export type PutApiQuoteOfferByIdStatusResponse = (unknown);

export type PutApiQuoteOfferByIdStatusError = unknown;

export type PutApiQuoteOfferByIdApprovalData = {
    path: {
        id: string;
    };
    query?: {
        Comment?: string;
        NewStatus?: ClientApprovalStatus;
        option?: number;
    };
};

export type PutApiQuoteOfferByIdApprovalResponse = (unknown);

export type PutApiQuoteOfferByIdApprovalError = unknown;

export type GetApiServiceData = {
    query?: {
        Id?: string;
        Price?: number;
        ServiceName?: string;
    };
};

export type GetApiServiceResponse = (unknown);

export type GetApiServiceError = unknown;

export type PostApiServiceData = {
    body?: Service;
};

export type PostApiServiceResponse = (unknown);

export type PostApiServiceError = unknown;

export type GetServiceData = {
    path: {
        id: string;
    };
};

export type GetServiceResponse = (unknown);

export type GetServiceError = unknown;

export type PutApiServiceByIdData = {
    body?: Service;
    path: {
        id: string;
    };
};

export type PutApiServiceByIdResponse = (unknown);

export type PutApiServiceByIdError = unknown;

export type DeleteApiServiceByIdData = {
    path: {
        id: string;
    };
};

export type DeleteApiServiceByIdResponse = (unknown);

export type DeleteApiServiceByIdError = unknown;